### ISSUE TITLE
Issue with valid V2 format

### ISSUE THREAD

**Issue by apeltzer** [lit-regensburg/samshee#5]
I have this samplesheet here that should be fine and passing validation, but I cannot get this to work. 

```bash
[Header]
FileFormatVersion,2
RunName,name123456
InstrumentPlatform,NovaSeq
operator,personname

[Reads]
Read1Cycles,100
Read2Cycles,100
Index1Cycles,10
Index2Cycles,10

[Sequencing_Settings],
LibraryPrepKits,Illumina Stranded Total RNA Prep, Ligation with Ribo-Zero Plus (96 Samples)

[BCLConvert_Data]
Sample_ID,Index,Index2,Index name,someid,someotherid,time,TPT,Matrix,Organism,stdid, analyte,project_id,Study Category
.....

```

This unfortunately raises an error like this one: 

![image](https://github.com/user-attachments/assets/95c68b56-1404-4a26-9808-105e1953bfd0)

**Comment by apeltzer** [comment]
@grst for reference

**Comment by j4cko** [comment]
Hi @apeltzer, thanks for raising the issue. Unfortunately, I cannot reproduce your issue:
- The samplesheet you give (at least for me) has the only issue that the second column in the `Sequencing_Settings` should be quoted.
- Unfortunately, when exporting the sheet again, the result again is not quoted, I consider this a bug -> see issue #6 
Can you confirm that you do not get an error with the latest version on the input in the appendix?
[issue_5.csv](https://github.com/user-attachments/files/17946265/issue_5.csv)

**Comment by apeltzer** [comment]
I'll test this out, agree on your #6 issue to be an issue 👍🏻

**Comment by grst** [comment]
Hi @j4cko, 

thanks for your quick response. I played around a bit more and I think I've found a minimal example though I still don't understand the issue. Your `issue_5.csv` works, but this doesn't: 

**test2.csv**
```
[Header]
FileFormatVersion,2
RunName,name123456
InstrumentPlatform,NovaSeq
operator,personname

[Reads]
Read1Cycles,100
Read2Cycles,100
Index1Cycles,10
Index2Cycles,10

[Sequencing_Settings]
LibraryPrepKits,"QIAseq miRNA Library Kit"

[BCLConvert_Data]
Sample_ID,Index,Index2,Index name
sample1,TGAACGTTGT,AGTCGGCCAT,xxx
sample2,ACTGGCGAAC,TCGACTTATC,yyy
```

Notably, when only including exactly one line with sample1 or sample2, it works. 

I used the following command to run this with the latest version of samshee

```
uv tool run --from samshee==0.2.3 python -m samshee test2.csv
```

**Comment by j4cko** [comment]
Hi, thanks very much, I can reproduce this now. The issue is that it is assumed that if there is a `BCLConvert_Data` section, there must also be a `BCLConvert_Settings` section - which is not the case in your example. This requirement is probably okay, because t[he "spec" ](https://help.connected.illumina.com/run-set-up/overview/instrument-settings/nextseq-1000-2000-settings) says that `BCLConvert_Settings.SoftwareVersion` is a required property.

I still see an issue here: 
1) The error message should be less cryptic and clearly state what is wrong with the sheet.
2) I think the way this is parsed and checked is not very concise and might contain errors. I think there is some rework required.

In your workflow, is there a reason to deviate from the illumina spec (i.e. having a `BCLConvert_Data` section but no `BCLConvert_Settings` section?

**Comment by apeltzer** [comment]
Can confirm that this indeed fixed it, thank you @j4cko - agree that the error message should be a bit more explicit if possible. 

There is no real reason for this - our main intent was to have a proper validation of samplesheets set up in the nf-core/demultiplexing pipeline & the template we tried building wasn't having this as we deemed it optional. Seems like I should read the "specs" more carefully 😆
